set -g allow-passthrough on
set -s extended-keys on
set -s set-clipboard on
set -s get-clipboard request
set -as terminal-features "xterm*:extkeys"
set -as terminal-features "xterm-ghostty:hyperlinks:osc7:overline:progressbar:usstyle"
